apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "surveyjs-validator.fullname" . }}
data:
  VERSION: {{ .Values.image.tag | default .Chart.Version }}

  {{ if .Values.openTelemetry.enabled }}
  OTEL_ENABLED: "true"
  OTEL_SERVICE_NAME: {{ include "surveyjs-validator.fullname" . | quote }}
  # https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/#protocol-configuration
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.openTelemetry.otlp.endpoint | quote }}
  OTEL_EXPORTER_OTLP_PROTOCOL: {{ .Values.openTelemetry.otlp.protocol | quote }}
  OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: {{ .Values.openTelemetry.otlp.protocol | quote }}
  OTEL_EXPORTER_OTLP_METRICS_PROTOCOL: {{ .Values.openTelemetry.otlp.protocol | quote }}
  OTEL_EXPORTER_OTLP_LOGS_PROTOCOL: {{ .Values.openTelemetry.otlp.protocol | quote }}
  {{else}}
  OTEL_ENABLED: "false"
  {{end}}
