{{ if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "surveyjs-validator.fullname" . }}
  labels:
    {{- include "surveyjs-validator.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "surveyjs-validator.selectorLabels" . | nindent 4 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - path: /metrics
    - port: metrics
      interval: 10s
{{ end }}
