name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          tag_prefix: v
      - name: Trigger CI build
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{secrets.CI_WEBHOOK_URL}}'
          method: 'POST'
